TARGET =	project
LIBS =		-lsimple -lcheck -lsuif -luseful
OBJS =		doproc.o main.o Graph.o DataFlow.o LICM.o print.o Common.o

all:            $(TARGET)
install-bin:    install-prog

include $(SUIFHOME)/Makefile.std

